### ISSUE TITLE
Border attribute is not taken into account when calculating height

### ISSUE THREAD

**Issue by thijs-qv** [jsamr/react-native-render-html-table-bridge#8]
If you have a border attribute on the table, eg.
`<table border="1">...</table>` it is not taken into account when calculating height (using autoheight: true).

**Comment by maicolsantos** [comment]
the following code snippet works to me, for now.
I'm waiting for an official fix.

```
alterChildren={(node) => {
  if (node.name === 'table') {
    node.attribs._rawHtml = node.attribs._rawHtml.replace(/border="\d"/g, '')
  }
}
```

**Comment by jsamr** [comment]
@thijs-qv @maicolsantos This is [likely a box-sizing issue](https://www.w3schools.com/css/css3_box-sizing.asp).

Can you try to add a CSS rule for the table element as such, and tell me if the issue disappear?

```css
table {
  box-sizing: border-box;
}
```

**Comment by thijs-qv** [comment]
I've added the rule to css-rules.js, but the issue still persists.

**Comment by jsamr** [comment]
OK. Please provide me [a minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) (ideally, a git), and I'll be happy to investigate.

**Comment by thijs-qv** [comment]
I've placed a simple example [here](https://github.com/thijs-qv/rnrhtb-example).
Would be great if you can take a look.

**Comment by jsamr** [comment]
@thijs-qv @maicolsantos This is my understanding of the issue so far:

1. The `border` table attribute is a legacy from old HTML specs, and is not part of the HTML 5 standard anymore.
2. The `border` table attribute is ignored when my script computes table's height because it uses, for best browser support, the [scrollHeight](https://www.w3schools.com/jsref/prop_element_scrollheight.asp).

I could probably just add the style's `borderWidth` value to the `scrollHeight` and it should fix the problem, if and only if browser engines transfer the legacy `border` property to the style object, which you will have to confirm.

I will publish pre-release patches that you can test, until the issue is resolved. Will keep you updated.

**Comment by thijs-qv** [comment]
Thanks for looking into it. I'm not sure if adding the `borderWidth` to the `scrollHeight` will solve the issue. The `border` attribute specifies if a border should be displayed around the table cells or not. So it's not just the table that gets a border, but the cells as well.

**Comment by jsamr** [comment]
@thijs-qv I don't think that is an issue because inner borders will be taken into account in `scrollHeight`. It did work on your MWE. Please test again with `0.5.1-rc.0`, and let me know :-)

**Comment by thijs-qv** [comment]
@jsamr You are correct, that is not an issue, it's working well now. Thank you / merci beaucoup!

**Comment by jsamr** [comment]
@thijs-qv You're very welcomed!

**Comment by maicolsantos** [comment]
@jsamr it's working well now. Thank you 🤓

**Comment by jsamr** [comment]
@maicolsantos I realize you're from Fortaleza, aren't you? I've just moved from France to Juazeiro do Norte, what a coincidence!

**Comment by maicolsantos** [comment]
@jsamr I sent you an email. 🤓
